### ISSUE TITLE
Convert image api

### ISSUE THREAD

**Issue by SchweinchenFuntik** [MolotovCherry/kmagick#13]
JPEG convert to BMP.
looking for a good image format envelope library

**Comment by MolotovCherry** [comment]
> looking for a good image format envelope library
Not sure what you mean here. What are you looking for exactly?

But in either case, this project is only bindings to the underlying imagemagick lib, whichever one is used (whether windows dll or android so, or whatever). The underlying lib is the one that is able to open different image types as well as convert them. So these bindings have no ability to change whether it can or can't open or convert different image types.

**Comment by SchweinchenFuntik** [comment]
Now imagemagick is used for converting, but in the form of a script. I want to replace this with a call from the code

Windows
`magick mogrify -path path -format bmp  *png`

**Comment by MolotovCherry** [comment]
> Now imagemagick is used for converting, but in the form of a script. I want to replace this with a call from the code
> 
> Current command Windows `magick mogrify -path path -format bmp *png`

You should be able to simply open the image and save it. This will convert it.
Please see the [example](https://github.com/MolotovCherry/kmagick/blob/main/example/src/main/kotlin/com/example/cli/Main.kt) for more
```kotlin
    // close resources when finished
    Magick.initialize().use {
        val wand = MagickWand()

        wand.readImage("blah.jpeg")

        // write result out
        wand.writeImage("D:/out.png")
```
