### ISSUE TITLE
UnableToReadFont

### ISSUE THREAD

**Issue by MansonLuo** [MolotovCherry/kmagick#18]
Just want to update you. The reason it fails is because the font isn't available. (The Exception message I showed above will tell you that as well)

_Originally posted by @MolotovCherry in https://github.com/MolotovCherry/kmagick/issues/1#issuecomment-1067941160_

**Comment by MansonLuo** [comment]
Try Candice font, still cannot read font

**Comment by MolotovCherry** [comment]
Have you [checked](https://github.com/MolotovCherry/kmagick#exceptions) the exceptions? Or do you get another error? What do you see?

**Comment by MansonLuo** [comment]
I use method you provided that get exception from MagicWand.
I use kmagic in android kotlin, but can't read font, is there a way to find font in android

**Comment by MolotovCherry** [comment]
I am uncertain since imagemagick itself is throwing the error. But a good start would be to see how imagemagick itself finds fonts.

**Comment by MansonLuo** [comment]
I'm glad to do that 🙂
